### ISSUE TITLE
Designideen für Sudoku Startseite sammel

### ISSUE THREAD

**Issue by ghost** [Haus4/project-server#11]
Schaut euch mal Sudoku Seiten / Zeug an, damit wir eine Vorstellung bekommen.

**Comment by MuellerMP** [comment]
UI-Konzept von mir (was derzeitig auch der Stand vom Code ist) war:
- am anfang **Schwierigkeit zu wählen**
- **Sudoku-Feld als tabelle** in JSP
- **Onclick** events auf jedem feld (sollte am besten nur auf nicht ausgefüllten Feldern möglich sein bzw User-Input-Feldern), welche ein **Input-Feld für den User Input** erstellen
-  Bei "Enter" soll das **Inputfeld entfernt** werden und der **Wert wird gespeichert**

Jedoch würde ich persönlich diese Variante nicht bevorzugen, da der code schnell unlesbar wird - Alternative wäre z.b. **Input-Buttons mit Zahlen** vorzugeben.

**Comment by MuellerMP** [comment]
Beispiel:
![sudoku-design](https://cloud.githubusercontent.com/assets/28714325/26242393/91ad0608-3c88-11e7-87ba-cbd9f084ee5c.PNG)

**Comment by MuellerMP** [comment]
^- hier kann man auch Merker durch Inputfeld unter dem nummern-Schaltfeld realisieren
