### ISSUE TITLE
Eclipse setup erklären/aufsetzen

### ISSUE THREAD

**Issue by Haus4** [Haus4/project-server#9]
explain local setup

**Comment by ghost** [comment]
Git herunterladen
https://git-scm.com/download/win

**Comment by MuellerMP** [comment]
SCHRITT 1:
Git runterladen (https://git-scm.com/downloads)
SCHRITT 2:
Git installieren (am besten nichts an den Standart-Einstellungen verändern)
SCHRITT 3:
Projekt-Ordner anlegen
SCHRITT 4:
Rechtsklick im Projekt-Ordner -> Git BASH öffnen
SCHRITT 5:
`git clone https://github.com/Haus4/project-server.git` [ENTER]
SCHRITT 6:
Webengineering-Eclipse öffnen -> Workspace = projekt ordner
SCHRITT 7:
Rechtsklick -> Import -> Maven -> Existing Maven Projekt -> *Geklonter Projekt Ordner*
SCHRITT 8:
Rechtsklick auf Projekt -> Properties -> Project Facets -> Runtime auf localen Tomcat ändern
